name: cv_test
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312he558020_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - cairo=1.16.0=haedb8bc_5
  - eigen=3.4.0=h59b6b97_0
  - expat=2.6.2=hd77b12b_0
  - fontconfig=2.14.1=hb33846d_3
  - freetype=2.12.1=ha860e81_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - graphite2=1.3.14=hd77b12b_1
  - gst-plugins-base=1.22.3=hfc3ed34_1
  - gstreamer=1.22.3=h1779075_1
  - harfbuzz=4.3.0=hb646838_2
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - jpeg=9e=h827c3e9_3
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_h5da7b33_0
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libogg=1.3.5=h2bbff1b_1
  - libopencv=4.10.0=haa95532_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libtiff=4.5.1=hd77b12b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.13.1=h24da03e_2
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.8=py312h2bbff1b_0
  - mkl_random=1.2.4=py312h59b6b97_0
  - numexpr=2.8.7=py312h96b7d27_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - opencv=4.10.0=py312h4ccfa20_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.15=h827c3e9_0
  - pandas=2.2.2=py312h0158946_0
  - pcre2=10.42=h0ff8eda_1
  - pip=24.2=py312haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - py-opencv=4.10.0=haa95532_0
  - python=3.12.4=h14ffc60_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312haa95532_0
  - qt-main=5.15.2=h19c9488_10
  - setuptools=72.1.0=py312haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.40=h2eaa2aa_0
  - vs2015_runtime=14.40.33807=h98bb1dd_0
  - wheel=0.43.0=py312haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.5=hd43e919_2
  - pip:
      - altgraph==0.17.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - fonttools==4.53.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - openpyxl==3.1.5
      - packaging==24.1
      - pefile==2024.8.26
      - pillow==10.4.0
      - pyinstaller==6.10.0
      - pyinstaller-hooks-contrib==2024.8
      - pyparsing==3.1.4
      - pyside6==6.7.2
      - pyside6-addons==6.7.2
      - pyside6-essentials==6.7.2
      - pywin32-ctypes==0.2.3
      - shiboken6==6.7.2
prefix: F:\anaconda3\envs\CV
